### ISSUE TITLE
Enabling Moon Jump breaks certain things.

### ISSUE THREAD

**Issue by wiznillyp** [MorsGames/sm64plus#20] opened 2021-04-20 13:41 UTC
v1.1.2.1
Windows 10 64-bit
Xinput controls

Enabling moon jump seems to interrupt many jumping techniques.

Here are the few that I have found:

1. When, doing a long jump, the animation for the long jump will change from Mario's feet leading to a normal jumping animation with his fist upward and the momentum will change.
2. Wing Cap does not fly, same idea as 1, the flip-to-flying animation gets interrupted and Mario falls back to the ground.
3. You can not enter Boo's Mansion (level 5).  The spinning-and-shrinking animation gets interrupted and the level entrance remains on the ground with no way to re-enter.
4. Pretty much any jumping animation.

**Comment by MorsGames** [comment] 2021-04-21 08:29
That option is a straight port of a really old GameShark code with the same name, and was intended less for actual debugging, and more as an easter egg for those who are nostalgic. The original code itself has the same issues too, you can try it on an emulator and see.

I guess I can add an extra option for that setting that fixes those issues and make it usable though.

**Comment by wiznillyp** [comment] 2021-04-21 09:07
Thanks for taking time to review this.  I did not know about the game genie code.

Moon Jump is pretty game-breaking, it might be worth just updating the descriptive text for now.

Perhaps add this to a FAQ or Readme: "Moon Jump breaks almost all of Mario's movements, Flight does not work with wing cap and its not possible to enter Level 5 Big Boo's Haunt."

I can do a PR if needed, but its probably easier for you to batch it with your next update.

**Comment by MorsGames** [comment] 2021-04-21 09:14
I mean it would be a pretty easy fix for me to implement regardless, I'll do that in the next update.

**Comment by MorsGames** [comment] 2021-04-23 09:15
It's now added to the game so I can close this.

**Closed by MorsGames** 2021-04-23 09:15 UTC
Labels: bug
