### ISSUE TITLE
I cant Install the game

### ISSUE THREAD

**Issue by theostein** [MorsGames/sm64plus#28] opened 2021-05-18 17:49 UTC
Ive kept trying to install the game but this keeps popping up Warnung: database file for 'clang64' does not exist (use '-Sy' to download)

Couldn't install the prerequisites.
Press any key to close this window.

**Comment by MorsGames** [comment] 2021-05-19 09:28
As the [FAQ](https://github.com/MorsGames/sm64plus/blob/master/FAQ.md) suggests, disabling your antivirus, reinstalling MSYS2, and deleting the "sm64plus" folder fixes issues like that for most people. If you're having further problems as for help in our Discord server.

Closing, since the issue isn't directly related to the game.

**Closed by MorsGames** 2021-05-19 09:28 UTC
